name: Push Tag on Package Version Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Get package version
        id: get-package-version
        run: echo "package_version=$(poetry version | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Check if a tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: v${{ steps.get-package-version.outputs.package_version }}

      - name: Push tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git tag v${{ steps.get-package-version.outputs.package_version }}
          git push origin v${{ steps.get-package-version.outputs.package_version }}
