name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v4
        with:
          # Comply with https://github.com/commitizen/conventional-commit-types/blob/c3a9be4c73e47f2e8197de775f41d981701407fb/index.json
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          subjectPattern: ^(?![A-Z]).+$
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
